name: 'Lighthouse Check with PageSpeed Insights'
description: 'GitHub Action for running one or multiple Lighthouse audits featuring PR comments, Slack notifications and more!'
inputs:
  apiToken:
    description: 'The foo.software account API token found in the dashboard.'
    required: false
  author:
    description: 'For Slack notifications: A user handle, typically from GitHub.'
    required: true
  awsAccessKeyId:
    description: 'The AWS accessKeyId for an S3 bucket.'
    required: false
  awsBucket:
    description: 'The AWS Bucket for an S3 bucket.'
    required: false
  awsRegion:
    description: 'The AWS region for an S3 bucket.'
    required: false
  awsSecretAccessKey:
    description: 'The AWS secretAccessKey for an S3 bucket.'
    required: false
  branch:
    description: 'For Slack notifications: A version control branch, typically from GitHub.'
    required: true
  configFile:
    description: 'A configuration file path in JSON format which holds all options defined here. This file should be relative to the file being interpretted. In this case it will most likely be the root of the repo ("./")'
    required: false
  commentUrl:
    description: "An endpoint to post comments to. This is only needed if you want to trigger comments on 'push'. A 'pull_request' trigger does not require this to be set. Typically this will be from GitHub's API. Example: https://api.github.com/repos/:owner/:repo/commits/:commit_sha/comments."
    required: false
  emulatedFormFactor:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module for details.'
    required: false
  extraHeaders:
    description: 'Stringified HTTP Header object key/value pairs to send in requests.'
    required: false
  locale:
    description: 'A locale for Lighthouse reports. Example: ja'
    required: false
  outputDirectory:
    description: 'An absolute directory path to output report. You can do this an an alternative or combined with an S3 upload.'
    required: true
  overridesJsonFile:
    description: 'A JSON file with config and option fields to overrides defaults.'
    required: false
  pr:
    description: 'For Slack notifications: A version control pull request URL, typically from GitHub.'
    required: false
  prCommentEnabled:
    description: 'If true and accessToken is set scores will be posted as comments.'
    required: false
  prCommentSaveOld:
    description: 'If true and PR comment options are set, new comments will be posted on every change vs only updating once comment with most recent scores.'
    required: false
  accessToken:
    description: 'Access token of a user to post PR comments.'
    required: false
  sha:
    description: 'For Slack notifications: A version control sha, typically from GitHub.'
    required: false
  slackWebhookUrl:
    description: 'A Slack Incoming Webhook URL to send notifications to.'
    required: false
  tag:
    description: 'An optional tag or name (example: "build #2" or "v0.0.2").'
    required: false
  throttlingMethod:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module comments for details.'
    required: false
  throttling:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module comments for details.'
    required: false
  timeout:
    description: 'Minutes to timeout for remote runs. If "wait" option is "true" (it is by default), we wait for results. If this timeout is met before results are received an error is thrown.'
    required: false
  urls:
    description: 'A comma-separated list of URLs (or page API tokens if running remotely).'
    required: true
  verbose:
    description: 'If yes, logs output along each step.'
    required: false
  wait:
    description: 'If "true", for remote runs, waits for all audit results to be returned, otherwise URLs are only enqueued.'
    required: false
  psiKey:
    description: 'PageSpeed Insights API key.'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'zap'  
  color: 'green'